export const postConstants = {
  GET_ALL_POSTS: "GET_ALL_POSTS",
  GET_SINGLE_POST: "GET_SINGLE_POST",
  LIKE_POSTS: "LIKE_POSTS",
  EDIT_POST: "EDIT_POST",
  DELETE_POST: "DELETE_POST",
  CREATE_POST: "CREATE_POST",
};
