export const userConstants = {
  GET_ALL_USERS: "GET_ALL_USERS",
  FOLLOW_USER: "FOLLOW_USER",
  UNFOLLOW_USER: "UNFOLLOW_USER",
  SELECTED_USER_PROFILE: "SELECTED_USER_PROFILE",
  GET_BOOKMARKS: "GET_BOOKMARKS",
  BOOKMARK_POST: "BOOKMARK_POST",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",
  EDIT_USER: "EDIT_USER",
};
